runtime: nodejs16

env_variables:
  MONGOURI: "mongodb+srv://alfan:heathcliff123@cluster0.xzqwb.mongodb.net/med_reminder?retryWrites=true&w=majority"
  PASSWORD: "aethelwolf"
  EMAIL: "alfanfgifary18@if.unjani.ac.id"
  PORT: 8080
  NODE_ENV: "production"
  API_PROD: "http://34.101.83.49"
  API_LOCAL: "http://localhost:8080"
