runtime: nodejs16

env_variables:
  MONGOURI: "mongodb+srv://alfan:heathcliff123@cluster0.xzqwb.mongodb.net/med_reminder?retryWrites=true&w=majority"
  PASSWORD: "aethelwolf"
  EMAIL: "alfanfgifary18@if.unjani.ac.id"
  PORT: 8080
  NODE_ENV: "production"
  API_PROD: "http://34.128.119.246"
  API_LOCAL: "http://localhost:8080"
  GOOGLE_APPLICATION_CREDENTIALS: "./utils/medreminder-2e833-c52e4e327412.json"
