runtime: nodejs16

env_variables:
  MONGOURI: "mongodb+srv://alfan:heathcliff123@cluster0.xzqwb.mongodb.net/med_reminder?retryWrites=true&w=majority"
  PASSWORD: "aethelwolf"
  EMAIL: "alfanfgifary18@if.unjani.ac.id"
  TWILIO_SID_ACCOUNT: "AC2de8eb8bf3764bdde8549c6dbf472244"
  TWILIO_AUTH_TOKEN: "0162ad01ae280df70f05fcc3e16511be"
  PORT: 8080
